### ISSUE TITLE
Batches Profile 

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#48]
@sonu831 
**Describe the bug**
Unable to **edit batch** details 

**To Reproduce**
1. Go to Batches
2. Click on the existing batch 
3. Click on the edit button present at the top right corner of the screen.
4.  Make the required changes and click on the Ok(tick mark) at the top right corner of the screen.
5. See error

**Expected behavior**
Edit the batch details should enable us to make any necessary changes that the coach wants to do in the name/description of the batch

**Screenshots**
![WhatsApp Image 2023-12-02 at 1 34 19 PM](https://github.com/sonu831/SportEco/assets/152055921/38326917-6f1b-4dae-8b8e-ae33ae48a4a7)

**Comment by sonu831** [comment]
@prem-hariyal22 please look

**Comment by prem-hariyal22** [comment]
@Muffy1404  fixed
