### ISSUE TITLE
+ create player(BATCH PROFILE)

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#50]
**Describe the bug**
+create player in the batch profile is not letting create a new player 

**To Reproduce**
1. Go to one of the existing batch
2. Click on the + sign in the bottom right corner 
3. Scroll down to +create button present
5. See error

**Expected behavior**
Clicking on the + create player should ideally take us to the create player page 

**Screenshots**

https://github.com/sonu831/SportEco/assets/152055921/3c0e2cfb-fd1d-4b8e-af26-0445d644fc09

**Comment by Muffy1404** [comment]
High Priority

**Comment by sonu831** [comment]
@prem-hariyal22 please look

**Comment by prem-hariyal22** [comment]
fixed.
