### ISSUE TITLE
Add/Remove Player is not taking me to edit player page

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#55]
**Describe the bug**
Add/Remove player button should direct me to Edit player page whereas it is taking me to Add player making me unable to add or remove any player.

**To Reproduce**
1. Go to Edit Batch Details on Batches profile
2. Click on Add/Remove button at the bottom of the screen
3. See error

**Screenshots**

https://github.com/sonu831/SportEco/assets/152055921/d831b648-95f6-4c22-a7e6-10c612c3cacd

**Comment by Muffy1404** [comment]
High Priority

**Comment by Muffy1404** [comment]
Uploading WhatsApp Video 2023-12-25 at 11.47.29 PM.mp4…
The option to add/remove is still not working properly 
not letting to remove any player from a batch

**Comment by sonu831** [comment]
@prem-hariyal22 please check

**Comment by Muffy1404** [comment]
While removing a player from a batch warning pop up is not appearing on the screen
After adding a player in a batch the page is stuck at the same place even after clicking the tick button

**Comment by prem-hariyal22** [comment]
@Muffy1404 @sonu831 fixed.
