### ISSUE TITLE
Message - Cannot read property "length" of undefined 

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#56]
**Describe the bug**
During testing the delete batch option a message appeared on the screen saying "Cannot read property "length" of undefined"

**Screenshots**

![WhatsApp Image 2023-12-11 at 10 59 42 PM](https://github.com/sonu831/SportEco/assets/152055921/9d0d0e42-e905-4cc5-be51-70b27b22364c)

**Comment by Muffy1404** [comment]
High Priority

**Comment by prem-hariyal22** [comment]
@sonu831  fixed yesterday.
