### ISSUE TITLE
Delete Batch option Not showing the Warning message

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#57]
**Describe the bug**
Delete batch option is not showing the warning message as per Figma and working is also not to the point 

**Expected behavior**
Upon clicking on the Delete Batch option present on the edit batch page a warning message is supposed to pop up confirming the action as per the figma and delete batch option is also working a bit differently which is shown in the video below

**Screenshots**

https://github.com/sonu831/SportEco/assets/152055921/b08a31e8-8289-4a9d-a2f9-2081697351e4

Comment
High Priority

**Comment by sonu831** [comment]
@prem-hariyal22 please look into this

**Comment by Muffy1404** [comment]
As per the latest build the message was yet not shown before deleting the batch

**Comment by prem-hariyal22** [comment]
@Muffy1404 @sonu831 fixed this.
