### ISSUE TITLE
Font Colour of the Batch's name and Description is different

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#58]
**Describe the bug**
The font colour while typing the Batch's name and description is different as per Figma 

**Screenshots**
![WhatsApp Image 2023-12-11 at 11 22 22 PM](https://github.com/sonu831/SportEco/assets/152055921/f7b9b84a-9f60-48d8-a2c8-5628b89a6efa)

**Additional context**
Low Priority

**Comment by sonu831** [comment]
@prem-hariyal22 please look into this

**Comment by prem-hariyal22** [comment]
@sonu831 this issue may be fixed before. because there are no color issue in create batch form.

**Comment by sonu831** [comment]
May be we need to ch ckeck the build

**Comment by Muffy1404** [comment]
1.The font colour while writing the entering the name in create profile is not matching, it needs to be fixed
2.Also as per figma, while entering details first name last name should appear at the top of the boxes which is also missing
3. The black box appearing in DOB is not as per design
![WhatsApp Image 2023-12-25 at 11 40 09 PM](https://github.com/sonu831/SportEco/assets/152055921/5505e96f-7ddb-4bed-969a-d044a59152ef)

**Comment by prem-hariyal22** [comment]
fixed
