### ISSUE TITLE
Delete Player button is slight different from the figma screen 

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#66]
**Describe the bug**
The delete Player button in the figma contains a bin icon whereas the app doesn't

**Screenshots**
![Screenshot_20231226_132401.jpg](https://github.com/sonu831/SportEco/assets/152055921/b492d05e-c014-4cc9-aacd-cca4c9ef2e65)

**Comment by prem-hariyal22** [comment]
@sonu831 @Muffy1404  fixed.
