### ISSUE TITLE
The consecutive pages are missing when clicking on the view full profile on Player profile 

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#67]
**Describe the bug**
A clear and concise description of what the bug is described in the screen recording video below.

**Screenshots**https://github.com/sonu831/SportEco/assets/152055921/aea864f6-79dd-459b-be49-46d42f8fe332

**Comment by prem-hariyal22** [comment]
@Muffy1404  @sonu831  fixed.
