### ISSUE TITLE
Placement of OTHER button is different

### ISSUE THREAD

**Issue by Muffy1404** [sonu831/SportEco#68]
**Describe the bug**
The Placement of OTHER button on select gender on create profile page is different as per figma

**Screenshots**

![Screenshot_20231226_134119.jpg](https://github.com/sonu831/SportEco/assets/152055921/0e4543ce-3eb8-425d-8af8-01bc9bfacc63)

**Comment by prem-hariyal22** [comment]
@sonu831 @Muffy1404  fixed.
